'use strict';
// DOM integration tests. These do not claim browser rendering or audio quality.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');const {route,finishDialogue}=require('./route.cjs');
const root=path.resolve(__dirname,'..');
function app(saved,opts={}){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script src="[^"]+"><\/script>/g,'');
 const dom=new JSDOM(html,{url:'https://nacre.test',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
 w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'));};
 w.HTMLMediaElement.prototype.pause=function(){};w.HTMLMediaElement.prototype.play=function(){return Promise.resolve();};
 w.URL.createObjectURL=()=> 'blob:nacre-test';w.URL.revokeObjectURL=()=>{};
 w.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};
 const utterances=[];w.speechSynthesis={getVoices:()=>[{name:'Français local',lang:'fr-FR',voiceURI:'local-fr',localService:true}],cancel:()=>{},speak:u=>utterances.push(u),addEventListener:()=>{}};
 if(saved){w.localStorage.setItem('nacre.v1.auto',JSON.stringify(saved));w.localStorage.setItem('nacre.v1.meta',JSON.stringify(saved.meta));}
 if(opts.corruptMeta)w.localStorage.setItem('nacre.v1.meta','{"endings":"broken","achievements":null}');
 if(opts.noStorage){Object.defineProperty(w,'localStorage',{get(){throw Error('Blocked storage');}});}
 for(const p of ['content','engine','audio','app'])w.eval(fs.readFileSync(path.join(root,'src',p+'.js'),'utf8'));
 const query=s=>w.document.querySelector(s),click=(a,id)=>{const selector=`[data-action="${a}"]${id?`[data-id="${id}"]`:''}`,el=query(selector);assert(el,'Missing '+selector);assert(!el.disabled,'Disabled '+selector);el.click();};
 return{dom,w,query,click,errors,utterances,state:()=>JSON.parse(w.localStorage.getItem('nacre.v1.auto'))?.state,close:()=>dom.window.close()};
}
function advance(a){let max=20;while(a.query('[data-action="advance"]')&&max--)a.click('advance');assert(max>0);}
function choice(a,i=0){const b=a.query(`[data-action="choice"][data-index="${i}"]`);assert(b&&!b.disabled);b.click();}
function dialogue(a,index=0){let n=0;while(a.query('[data-action="advance"]')||a.query('[data-action="choice"]')){assert(++n<40);if(a.query('[data-action="advance"]'))a.click('advance');else{choice(a,index);index=0;}}}
test('Accueil, tutoriel, dialogues et arrivée au marché par les commandes',()=>{const a=app();a.click('new');assert(a.query('#modal').open);a.click('start','normal');assert(a.query('#modal').open);a.click('close');dialogue(a);assert.equal(a.state().room,'harbor');assert(a.state().flags.welcome);a.click('spot','crate');dialogue(a);assert.equal(a.state().inventory.herb,6);a.click('echo');assert(a.query('[data-id="echo1"]'));a.click('spot','echo1');dialogue(a);assert(a.state().flags.echo_harbor);a.click('move','market');dialogue(a);assert(a.state().flags.archive_open);assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
test('Carte, inventaire, journal, liens, atlas, réglages et sauvegardes se rendent sans erreur',()=>{const g=route();g.s.dialogue=null;g.s.room='camp';const a=app(g.export());a.click('continue');for(const action of['map','inventory','journal','companions','gallery','settings','saves','help']){a.click(action);assert(a.query('#modal').open,action);assert(a.query('#modal-title').textContent);assert(a.query('.modal-body').textContent.length>30);a.click('close');}assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
test('Énigme cliquable, indice, remise à zéro et reprise',()=>{const g=route();g.s.dialogue=null;g.s.room='archive';delete g.s.flags.puzzle_archive;delete g.s.flags.lens;const a=app(g.export());a.click('continue');a.click('spot','seal');assert(a.query('.puzzle-console'));a.query('[data-action="dial"][data-index="0"]').click();a.click('hint');assert(a.query('.puzzle-hint').textContent.includes('lune'));a.click('reset-puzzle');assert.deepEqual(a.state().puzzle.values,[3,3,3]);for(const[i,n]of[1,2,3].entries())for(let j=0;j<n;j++)a.query(`[data-action="dial"][data-index="${i}"]`).click();a.click('check-puzzle');assert(a.state().flags.puzzle_archive);assert.equal(a.state().puzzle,null);assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
test('Combat : actions, victoire pacifique et reprise par l’interface',()=>{const g=route();g.s.dialogue=null;g.s.room='jetty';delete g.s.flags.won_jetty;g.s.hp=128;g.s.focus=9;const a=app(g.export());a.click('continue');a.click('spot','watch');assert(a.query('.combat-actions'));a.click('combat','calm');assert.equal(a.state().battle.calm,1);a.click('combat','calm');assert.equal(a.state().battle.result,'win');a.click('end-battle');assert(a.state().flags.won_jetty);assert(!a.state().battle);assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
test('Sauvegarde manuelle et chargement restaurent exactement le lieu',()=>{const g=route();g.s.dialogue=null;g.s.room='camp';const a=app(g.export());a.click('continue');a.click('saves');a.click('manual-save','slot1');a.click('close');a.click('move','market');a.click('saves');a.click('load-save','slot1');a.click('do-load','slot1');assert.equal(a.state().room,'camp');assert.equal(a.query('#modal').open,false);assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
test('Les six écrans de fin sont accessibles par les choix de l’interface',()=>{for(let i=0;i<6;i++){const g=route();const a=app(g.export());a.click('continue');advance(a);choice(a,i);assert(a.query('.choice-consequence'));a.click('advance');assert(a.query('.ending-screen'));assert.equal(a.state().ending,['shared','tide','dawn','sacrifice','crown','departure'][i]);assert(a.query('.ending-content').textContent.length>800);a.click('gallery');a.click('endings');assert(a.query('#modal').textContent.includes('Une autre rive'));assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();}});
test('Le jeu démarre avec des métadonnées corrompues ou un stockage indisponible',()=>{for(const opts of[{corruptMeta:true},{noStorage:true}]){const a=app(null,opts);a.click('new');a.click('start','story');if(a.query('#modal').open)a.click('close');assert(a.query('.narrative'));assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();}});
test('Les voix s’arrêtent sans reprendre les phrases déjà annulées',()=>{const a=app();a.click('settings');a.click('preview-voice');assert.equal(a.utterances.length,1);const u=a.utterances[0];a.click('stop-voice');u.onend();assert.equal(a.utterances.length,1);a.click('preview-voice');assert.equal(a.utterances.length,2);const v=a.utterances[1];a.click('close');v.onend();assert.equal(a.utterances.length,2);a.close();});
test('Navigation clavier et paramètres de lisibilité',()=>{const g=route();g.s.dialogue=null;g.s.room='camp';const a=app(g.export());a.click('continue');a.w.document.dispatchEvent(new a.w.KeyboardEvent('keydown',{key:'j'}));assert(a.query('#modal-title').textContent.includes('carnet'));a.w.document.dispatchEvent(new a.w.KeyboardEvent('keydown',{key:'Escape'}));assert(!a.query('#modal').open);a.click('settings');const f=a.query('#font');f.value='1.3';f.dispatchEvent(new a.w.Event('change',{bubbles:true}));assert.equal(a.w.document.documentElement.style.getPropertyValue('--fs'),'1.3');assert.equal(a.errors.length,0,a.errors.join('\n'));a.close();});
